### ISSUE TITLE
how to solve this issue

### ISSUE THREAD

**Issue by KhanHamidkhan** [strongloop/loopback-example-passport#100] opened 2017-11-10 16:47 UTC

**Comment by KhanHamidkhan** [comment] 2017-11-10 16:48
"Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.""

**Comment by dhmlau** [comment] 2017-11-11 04:57
Duplicate of https://github.com/strongloop/loopback-example-passport/issues/101.

**Closed by dhmlau** 2017-11-11 04:57 UTC
