### ISSUE TITLE
User afterRemote('create' not firing after adding passport

### ISSUE THREAD

**Issue by mikesparr** [strongloop/loopback-example-passport#42] opened 2015-07-01 21:11 UTC
I added a `user.js` file to this project and an email DS, etc.  When I add some functionality for lost password, reset, etc. it works.  When I try to add email verification to this app, it fails and the remote hook never gets fired.

Is there any reason why `User.create` is not working during signup when the `User.create(newUser, ...` is in the signup route and I add remote hook?  Since `user.json` extends `User` model in core, do we have to somehow register the `create` remote method?

Added email verification from the `loopback-faq-user-management` example app and `User.afterRemote('create'` fails 
~~~
var path = require('path');
var app = require(path.resolve(__dirname, '../../server/server'));

module.exports = function(user) {
  //send verification email after registration
  user.afterRemote('create', function(context, user, next) {
    console.log('> user.afterRemote triggered');

    var options = {
      type: 'email',
      to: user.email,
      from: 'noreply@myco.com',
      subject: 'Thanks for registering.',
      template: path.resolve(__dirname, '../../server/views/pages/verify.jade'),
      redirect: 'pages/verified',
      user: user
    };

    user.verify(options, function(err, response) {
      if (err) {
        next(err);
        return;
      }

      console.log('> verification email sent:', response);

      context.res.render('pages/response', {
        title: 'Signed up successfully',
        content: 'Please check your email and click on the verification link '
          + 'before logging in.',
        redirectTo: '/',
        redirectToLinkText: 'Log in'
      });
    });
  });

  //send password reset link when requested
  user.on('resetPasswordRequest', function(info) {
    var url = 'http://' + app.get('email_link_domain') + '/reset-password';
    var html = 'Click <a href="' + url + '?access_token=' + info.accessToken.id
      + '">here</a> to reset your password';

    user.app.models.Email.send({
      to: info.email,
      from: info.email,
      subject: 'Password reset',
      html: html
    }, function(err) {
      if (err) return console.log('> error sending password reset email');
      console.log('> sending password reset email to:', info.email);
    });
  });
};
~~~

**Comment by eugenehp** [comment] 2015-09-06 08:18
hey @mikesparr any progress on this?

**Comment by superkhau** [comment] 2015-09-08 23:18
Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by mikesparr** [comment] 2015-09-09 15:34
Hi @eugenehp  and @superkhau  I will be diving back in on the project using LB next week and report. I'll fork the example repo and repeat my steps and share.  Thanks.

**Comment by julien-sarazin** [comment] 2016-03-18 10:48
@superkhau @mikesparr 
Might have found the reason.
in user-identity.js, line 134 
```javascript
      userModel.findOrCreate({ where: query }, userObj, function (err, user) {
        if (err) {
          return cb(err);
        }
      ...
```
The method `findOrCreate` won't trigger the afterRemote `create`.

**Comment by superkhau** [comment] 2016-03-18 18:56
@julien-sarazin Would you like to submit a PR with the fix?

**Comment by talpasco** [comment] 2016-03-26 11:55
Same here...
user.afterRemote('create'... Never fires.
(so does user.verify)

BTW,
Couldnt find the 'findOrCreate' function anywhere in the solution.

**Comment by talpasco** [comment] 2016-03-27 21:49
@mikesparr ... where you able to get the user.afterRemote('create' event to fire?

**Comment by julien-sarazin** [comment] 2016-03-28 13:50
Hey, 

Sorry guys don’t have much time those days.
I’ll try next week.


On 18 March 2016 at 19:56:49, Simon Ho (notifications@github.com) wrote:

@julien-sarazin Would you like to submit a PR with the fix?

**Comment by jannyHou** [comment] 2016-03-28 17:51
@julien-sarazin thank you! 
@superkhau @mikesparr @talpasco @julien-sarazin I think for build-in method like `create`, we should use [operation hook](https://docs.strongloop.com/display/public/LB/Operation+hooks#Operationhooks-Hooks) instead of remote hook?
The hook looks like:
```
MyModel.observe('before save', function myFunction(ctx, next) {
//TODO
}
```
I am not sure if we support `user.afterRemote('create', myFunction(ctx,next) {
//TODO
}
```

**Comment by bialikover** [comment] 2016-03-30 00:19
+1 Same issue here, thought it was a misconfiguration but the remote hook on create is not being triggered.

**Comment by jannyHou** [comment] 2016-03-30 14:25
@bialikover could you try operation hook I mentioned above?
https://github.com/strongloop/loopback-example-passport/issues/42#issuecomment-202505594

**Comment by bialikover** [comment] 2016-03-30 14:50
@jannyHou It works, but since its operational, It will be triggered also on update. A condition inside the hook to verify if is a new record or an update will work, 

I tried `afterRemote('create)` in another model based on `User`, and it's being triggered.

**Comment by jannyHou** [comment] 2016-03-30 17:39
@bialikover thank you. I will label it as a bug since `afterRemote('build-in-method')` is not triggered properly.

**Comment by richardpringle** [comment] 2016-03-30 21:48
@jannyHou, can you make sure that the right people see this (mention their names in case they have unsubscribed)?

The reason the the *remote hook* isn't triggered, is because the *remote method* is never called. When a method is called on the back-end like that, `user.create`, operational hooks are triggered but remote hooks aren't. That is because back-end methods are not *remote operations*.

If you want a remote hook to be triggered, you should POST to `/api/users` and move the immediate login logic that happens after a user is created to your remote hook `beforeRemote('create', ...)`. If you are sending a verification email anyway, you probably want to remove the immediate login logic altogether.

**Comment by jannyHou** [comment] 2016-03-31 20:37
@julien-sarazin @mikesparr @bialikover @talpasco @eugenehp please check the perfect explanation from @richardpringle https://github.com/strongloop/loopback-example-passport/issues/42#issuecomment-203649243

So the remote hook would *ONLY* be triggered when you are calling it from remote, which could be explorer in our case.
Let's reproduce the difference of calling from **remote** and calling on **beck end**:
[1]. Define a `afterRemote` hook for `create`:
```
module.exports = function(Myuser) {
	Myuser.afterRemote('create', function(ctx, instance, next){
	    console.log('create called');
	    next();
	});
};
```
[2]. Add a boot script to call `create` on **back end**:
```
module.exports = function(app) {
  var myUser = app.models.myuser;
  var mySample = {
  	"username": "me",
  	"password": "hah",
  	"email": "haha@gmail.com"
  };
  myUser.create(mySample, function (err, user) {
     if (err) return cb(err);
     else console.log("created>>", user);
  });
};
```
[3]. Run `node .` so `Myuser.create()` will be called in boot script, you will see `afterRemote` is not triggered, since you are calling from **beck end**:
![not triggerd](https://cloud.githubusercontent.com/assets/12554153/14189987/4ccf44b2-f75e-11e5-9ece-50af1c409a6b.PNG)

[4]. Use `POST/ Myusers` to create a new user, you can see that the hook is triggered, because you all calling it from **Remote**:
![triggered](https://cloud.githubusercontent.com/assets/12554153/14190008/6b116752-f75e-11e5-951c-dc73ff447733.PNG)

**Comment by superkhau** [comment] 2016-03-31 21:13
>I think for build-in method like create, we should use operation hook instead of remote hook?

Sorry for the late reply, this one slipped by.

Yes, you should use operation hooks when you want to trigger actions based on model events (ie. when you call User.create). `loopback-example-user-management` was probably written before operational hooks became a feature.

In any case, it's just a simple example to show you how you can implement it in your own app. In most cases, you will be calling the remote method API to create a user from your front-end app (ie. POST to /api/user, therefore triggering the remote method anyways).

@jannyHou @richardpringle Can you guys update the verify function to use the `after save` op hook instead? Create the issue, TOB, etc.

**Comment by jannyHou** [comment] 2016-03-31 22:04
@superkhau thank you for confirming! issue created: https://github.com/strongloop-internal/scrum-loopback/issues/822
Will refactor it soon.

**Comment by jannyHou** [comment] 2016-04-01 17:25
I am closing it since the answer of question is clear now, and also created a pr for correcting old code. Please feel free to reopen it or ask questions if you are still confused.

**Closed by jannyHou** 2016-04-01 17:25 UTC
Labels: question
