### ISSUE TITLE
Missing page

### ISSUE THREAD

**Issue by PhilippeCorreges** [strongloop/loopback-example-passport#46] opened 2015-08-26 10:39 UTC
500 Error: Failed to lookup view "pages/link" in views directory 

The Jade page does not exist

**Comment by superkhau** [comment] 2015-08-27 00:12
Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by PhilippeCorreges** [comment] 2015-08-27 09:09
Hi Simon,

My repos are private but here is a way to reproduce :
- Clone loopback-example-passport on your desktop
- Click on Link social accounts to your account <http://localhost:3000/link> on the first page
- The bug appears. The page does not exist.

Cheers

Philippe

**Comment by GeoffreyEmery** [comment] 2015-11-12 23:49
here is a repo i am not sure why i am providing this but wheatever... 
https://github.com/GeoffreyEmery/Loopback-AuthBug
as you can see there is no view with /link in the partial view directory causing a error when you click on the link account buttons
this was caused by this checkin 
https://github.com/dstroot/loopback-example-passport/commit/f3d2845311f83be5aa66f22140a3cd1ed5743906
and is linked to these other same issues 
https://github.com/strongloop/loopback-example-passport/issues/28
https://github.com/strongloop/loopback-example-passport/issues/46
https://github.com/strongloop/loopback-example-passport/pull/35
https://github.com/strongloop/loopback-example-passport/pull/18

**Comment by superkhau** [comment] 2015-11-13 06:49
@jannyHou Please try to reproduce this locally with the sample repo provided by @GeoffreyEmery to confirm the issue.

**Comment by jannyHou** [comment] 2015-11-13 13:59
@superkhau okay let me try it.

**Comment by jannyHou** [comment] 2015-11-13 14:43
@GeoffreyEmery @superkhau And I think the problem is there is no link.jade file in /server/views/pages
but the route 
```app.get('/link', function (req, res, next){
  res.render('pages/link', {
    user: req.user,
    url: req.url
  });
});```
directs to that non-existed page.

**Comment by superkhau** [comment] 2015-11-13 21:49
@jannyHou Can you check the history to see if there ever was one? Or else you can just update the example and remove or update that feature accordingly.

**Comment by jannyHou** [comment] 2015-11-16 14:33
@superkhau  ok, no problem, I will look into it.

**Comment by superkhau** [comment] 2015-11-16 16:40
@jannyHou TY.

**Comment by GeoffreyEmery** [comment] 2015-11-21 02:38
all you need to do is go back to the checkin i listed above that is the last refrence

**Comment by jannyHou** [comment] 2015-11-26 18:01
`link.html`existed before, from https://github.com/strongloop/loopback-example-passport/blob/262599a1a033edbbb1efcc7e6d363622b898aaad/public/link.html#L10-L11 we can know that it implemented the same function(link social account to local account) as https://github.com/strongloop/loopback-example-passport/blob/master/server/views/pages/loginProfiles.jade#L15-L17
So it's only a duplicate link that appears on index page. I will create a pr to delete it, then that would be done.

**Comment by jannyHou** [comment] 2015-11-27 15:13
Fixed in this pr: https://github.com/strongloop/loopback-example-passport/pull/55

**Closed by jannyHou** 2015-11-27 15:13 UTC
Labels: #review, bug, triage

**Comment by handonam** [comment] 2015-12-16 23:15
Per https://github.com/strongloop/loopback-example-passport/issues/46#issuecomment-156450649

```JS
app.get('/link', function (req, res, next){
  res.render('pages/link', {
    user: req.user,
    url: req.url
  });
});
```

Should this line be removed since it doesn't have a page there? I was confused as to why it's still there when looking over the example.

**Comment by jannyHou** [comment] 2015-12-17 01:44
@handonam Thanks! I should remove that together.
